# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fireflys.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'fireflys.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfireflys.proto\")\n\x0c\x46ireflyState\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05phase\x18\x02 \x01(\x02\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2X\n\x07\x46irefly\x12)\n\tSyncState\x12\r.FireflyState\x1a\r.FireflyState\x12\"\n\x0bReportState\x12\r.FireflyState\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firefly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIREFLYSTATE']._serialized_start=17
  _globals['_FIREFLYSTATE']._serialized_end=58
  _globals['_ACK']._serialized_start=60
  _globals['_ACK']._serialized_end=82
  _globals['_FIREFLY']._serialized_start=84
  _globals['_FIREFLY']._serialized_end=172
# @@protoc_insertion_point(module_scope)
