# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fireflys.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'fireflys.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66ireflys.proto\"\x1a\n\x0cPhaseRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1e\n\rPhaseResponse\x12\r\n\x05phase\x18\x01 \x01(\x02\x32\x34\n\x07\x46irefly\x12)\n\x08GetPhase\x12\r.PhaseRequest\x1a\x0e.PhaseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fireflys_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHASEREQUEST']._serialized_start=18
  _globals['_PHASEREQUEST']._serialized_end=44
  _globals['_PHASERESPONSE']._serialized_start=46
  _globals['_PHASERESPONSE']._serialized_end=76
  _globals['_FIREFLY']._serialized_start=78
  _globals['_FIREFLY']._serialized_end=130
# @@protoc_insertion_point(module_scope)
